classDiagram
    class AudioItem {
        <<abstract>>
        #_id: number
        #_title: string
        #_author: string
        #_duration: number
        +id: number
        +title: string
        +author: string
        +duration: number
        +set duration(v: number) : void
        +getInfo()* : string
        +calculateSize()* : number
        +formatDuration() : string
    }

    class Track {
        -_genre: string
        +genre: string
        +set genre(v: string) : void
        +getInfo() : string
        +calculateSize() : number
    }

    class Podcast {
        -_progress: number
        +progress: number
        +set progress(v: number) : void
        +getInfo() : string
        +calculateSize() : number
    }

    AudioItem <|-- Track
    AudioItem <|-- Podcast
